name: Flutter Grocery App APK Builder

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version'
        required: false
        default: '3.19.3'
        type: string
      build_type:
        description: 'Build type'
        required: false
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'Shahikjahan100/grocery_app'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ github.event.inputs.flutter_version }}
          channel: 'stable'
      
      - name: Flutter doctor
        run: flutter doctor -v
      
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Gradle permissions
        run: |
          cd android
          chmod +x ./gradlew
      
      - name: Build APK
        run: |
          flutter clean
          
          # Force accept Android licenses
          yes | flutter doctor --android-licenses || true
          
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build apk --release --no-tree-shake-icons
          else
            flutter build apk --debug --no-tree-shake-icons
          fi
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: grocery-app-${{ github.event.inputs.build_type }}-apk
          path: build/app/outputs/flutter-apk/*.apk
